### ISSUE TITLE
Подскажите как пользоваться отчетами?

### ISSUE THREAD

**Issue by exhang** [Tooyz/moysklad#1]
Здравствуйте, подскажите как пользоваться отчетами, например DashboardReport с параметром day?

**Comment by Tooyz** [comment]
Обновил ридми по отчетам, описал этот случай. Еще пофиксил баг с неверным неймспейсом у EmptySpecs класса.
Выкатил новый релиз https://github.com/Tooyz/moysklad/releases/tag/0.2.1, обновите composer.json

**Comment by suasti** [comment]
Спасибо
