### ISSUE TITLE
Баг с архивными группами товаров

### ISSUE THREAD

**Issue by Breedinf** [Tooyz/moysklad#10]
Этот код:

```
$folder = ProductFolder::query($this->sklad, QuerySpecs::create([
                'maxResults' => 1,
                'limit' => 1,
            ]))->withExpand(Expand::create(['productFolder']))
               ->filter((new FilterQuery())
               ->eq("id", $folder_id))->get(0);
```

возвращает null для архивной группы товаров в отличие от 

```
$folder = ProductFolder::query($this->sklad, QuerySpecs::create([
                'maxResults' => 1,
                'limit' => 1,
            ]))->withExpand(Expand::create(['productFolder']))->byId($folder_id);
```

Для архивных товаров вроде бы работают оба варианта кода.

**Comment by Tooyz** [comment]
Попытался повторить. К примеру:
`https://online.moysklad.ru/api/remap/1.1/entity/productFolder/a03996ad-7ea2-11e7-7a6c-d2a900118a09` - работает
`https://online.moysklad.ru/api/remap/1.1/entity/productFolder?filter=id=a03996ad-7ea2-11e7-7a6c-d2a900118a09` - не работает
`https://online.moysklad.ru/api/remap/1.1/entity/productFolder?filter=id=a03996ad-7ea2-11e7-7a6c-d2a900118a09;archived=true` - работает
Вывод - нужно явно фильтровать архивные объекты.
```
ProductFolder::query($this->sklad, $qs)->filter(
            (new FilterQuery())
                ->eq("id", 'a03996ad-7ea2-11e7-7a6c-d2a900118a09')
                ->eq("archived", 'true')
        )->get(0);

```
