### ISSUE TITLE
Как добавить к заказу позиции?

### ISSUE THREAD

**Issue by exhang** [Tooyz/moysklad#12]
Здравствуйте, пытаюсь добавить позиции к заказу:

$res = new EntityList($ms);
foreach ($tovars as $tovar){

	$product = Product::query($ms)->byId($tovar[0]);
	$product->quantity = $tovar[1];
	$product->price = $tovar[2];
	$res->push($product); 
}

$newOrder = (new CustomerOrder($ms, [
	"name" => '1'
]))
	->buildCreation()
	->addCounterparty($client)
	->addOrganization($org)
	->addPositionList($res)
	->execute();

 Я пытаюсь в EntityList добавить все товары и потом создать заказ, получаю ошибку от execute. В тестах есть пример добавления 1 позиции - это работает,  если делать addPositionList(EntityList($ms,[$tovar1,$tovar2])) - то тоже работает, но иначе никак, ошибка execute.

MoySklad\Components\Http\MoySkladHttpClient->post()
MoySklad\Components\MassRequest->create()

Вопрос еще в том, можно ли как то посмотреть что возвращает сервер моегосклада, какую ошибку?

**Comment by Tooyz** [comment]
@exhang 
Ошибку гляну попозже. Лог последних 10 запросов/ответов - RequestLog::getList();

**Comment by exhang** [comment]
Я сравнил вывод мета-данных в надежде найти разницу между тем когда явно прописываем массив: new EntityList($ms,[$product0,$product1]); и когда "push'ем":
new EntityList($ms);
...
$res->push($product);
...

Между ними разницы нет вообще. Только 1 вариант работает, второй нет. Ошибка:
/vendor/tooyz/moysklad/src/Components/Http/MoySkladHttpClient.php:181]
/vendor/tooyz/moysklad/src/Components/Http/MoySkladHttpClient.php:60] MoySklad\Components\Http\MoySkladHttpClient->makeRequest()
vendor/tooyz/moysklad/src/Components/MutationBuilders/UpdateBuilder.php:26] MoySklad\Components\Http\MoySkladHttpClient->put()

Куда еще можно копать? Ведь разницы не должно быть, что мы создаем до этого массив и что мы прописываем переменную с массивом в методе?

**Comment by Tooyz** [comment]
@exhang 
Не должно. Попробовал создавать EntityList и с массивом, и пушить в него товары после создания, 
CustomerOrder создается и так и так.

В исключении у вас в стеке вызов к UpdateBuilder, а в первом сообщении вы используете CreationBuilder - не совсем понял, вы  CustomerOrder обновляете или создаете?

Какой запрос уходит в мойсклад? Можно глянуть в поле "req" возвращаемом в методе MoySklad\Components\Http\RequestLog::getLast()

Можно увидеть немного больше кода, $res я так понимаю это массив полученный из апи?

**Comment by exhang** [comment]
Да, тестировал разные способы, могу ввести в заблуждение. 

Вот тут мой код: https://gist.github.com/exhang/9cccf0d287fef7a8054a4226bdcb44d3
Тут логи и req: https://gist.github.com/exhang/98ccf56a85bdb523533e5dfaac41aff3

**Comment by exhang** [comment]
> Попробовал создавать EntityList и с массивом, и пушить в него товары после создания.

Действительно, рабоает.  Не работает только в случае перебора массива foreach или for и в цикле push'ать данные в EntityList. Ошибка тажа. Хотя данные в EntityList попадают.

**Comment by Tooyz** [comment]
А так отрабатывает?
```
$ar = [];
foreach ($tovars as $tovar){
	$product = Product::query($ms)->byId($tovar[0]);
	$product->quantity = $tovar[1]; 
	$product->price = $tovar[2]; 
	$ar[] = $product; 
}
$res = new EntityList($ms, $ar);
...
```
Нужно вызвать лог после execute(), а не после получения товара (и лучше убрать из него поле headers, там все таки авторизация).

**Comment by exhang** [comment]
Тоже самое: 
[/vendor/tooyz/moysklad/src/Components/Http/MoySkladHttpClient.php:181]
[/vendor/tooyz/moysklad/src/Components/Http/MoySkladHttpClient.php:51] MoySklad\Components\Http\MoySkladHttpClient->makeRequest()
[/vendor/tooyz/moysklad/src/Components/MassRequest.php:56] MoySklad\Components\Http\MoySkladHttpClient->post()
[/vendor/tooyz/moysklad/src/Components/MutationBuilders/CreationBuilder.php:30] MoySklad\Components\MassRequest->create()
[ms_test.php:265] MoySklad\Components\MutationBuilders\CreationBuilder->execute()

Проблема в том что после execute я не могу ничего вызвать, так как выполнение прерывается.

**Comment by exhang** [comment]
Действительно странно, что выполнение прерывается, чего не должно быть. Ввел массив данных что подгружается с mysql через sql mapper фреймворка fatfree. Код сработал без ошибки.

**Comment by exhang** [comment]
Проблема действительно в типах данных. При смене данных в правильный формат (id - string, остальное - int), все встало на свои места. Работает. Тикет можно закрывать.
