### ISSUE TITLE
Работа с дополнительными полями

### ISSUE THREAD

**Issue by AsheK** [Tooyz/moysklad#17]
Здравствуйте! Благодарю за Ваши труды, очень хорошая библиотека.
Есть вопрос касательно работы с дополнительными полями, а именно: как обновить значение уже имеющегося доп. поля в уже имеющемся товаре? Примера не нашёл, посему и пишу.

**Comment by Tooyz** [comment]
Спасибо за отзыв, извиняюсь за долгий ответ.

В ридми есть пример работы с атрибутами

```
$specs = LinkingSpecs::create([
                 "name" => "attributes", //в апи доп поля хранятся в поле attributes
                 "multiple" => true //и являются массивом
             ]);
$counterparty = $counterparty->buildUpdate()
    ->addAttribute($attribute, $specs)
    ->addAttribute($attribute2, $specs)
    ->execute();
```

Можно просто переписать имеющийся атрибут новым с таким же meta и id, но например с другим value.

**Comment by walma** [comment]
> ```
> 
> Можно просто переписать имеющийся атрибут новым с таким же meta и id, но например с другим value.

Каким образом это можно сделать? Как инициализируются атрибуты? 
Приведите пример, пожалуйста. Что скрывается за $attribute ?

**Comment by sdmitrymelnik** [comment]
> > ```
> > 
> > Можно просто переписать имеющийся атрибут новым с таким же meta и id, но например с другим value.
> > ```
> 
> Каким образом это можно сделать? Как инициализируются атрибуты?
> Приведите пример, пожалуйста. Что скрывается за $attribute ?
> 
> `->addAttribute((new Attribute($sklad, [ [ 'id' => '57305982-7841-11e9-9109-f8fc000049d9', 'value' => (new \DateTime())->format('Y-m-d H:i:s.000'), ], ] )), $specs )`
> так не работает

    $attribute = new Attribute($storage, [
            'id' => '', //ид атрибута
            'value' => '', //внимание на тип атрибута
         ]
    );
....
->addAttribute($attribute, $specs)
