### ISSUE TITLE
У вас постоянно падает печать документов при повышении нагрузки

### ISSUE THREAD

**Issue by Coun1er** [Tooyz/moysklad#18]
Салют парни. Не знаю как донести более точечно. ТП и соцсети вам ни чего не передают поэтому пишу тут.

Передайте там в раздел разработки, что бы починили раз и навсегда печать документов. Добавили там vps и запили резервные сервера. Sas сервис такого уровня не может падать в разгар продаж. А у вас печать постоянно падает при повышении нагрузки на нее. ПИПЕЦ просто.

Сорян за беспокойство не по теме. Но шанс того, что информация дойдет до получателя через вас гораздо выше, чем если ее передавать через ТП.

**Comment by Coun1er** [comment]
И да ребята, как можно такую плевую задачу чинить 2 часа? Когда как можно просто восстановится из бекапа или откатится на прошлую версию в гите.

**Comment by Tooyz** [comment]
Добрый день. Я не являюсь разработчиком "Мой склад", вам лучше написать куда-нибудь сюда https://github.com/moysklad.
