### ISSUE TITLE
Notice: Trying to get property of non-object in moysklad\src\Components\Http\MoySkladHttpClient.php on line 182

### ISSUE THREAD

**Issue by croupier** [Tooyz/moysklad#2]
$res = [{"errors":[{"error":"Доступ запрещен: у вас нет прав на создание данного объекта", // и т.д.

                if ( $res = \json_decode($res) ){
                    if ( $res->errors ){  // Тут $res - может быть массивом
                        $except = new ApiResponseException($req, $res);
                    }
                }

Это происходит при использовании EntityList->massCreate() когда нет прав на создание еntitiy

**Comment by Tooyz** [comment]
Я правильно понимаю, что вы хотите создать какие-то сущности не имея на это прав в аккаунте? Тогда это ожидаемое поведение. Если речь не об этом - поправьте меня.

**Comment by Tooyz** [comment]
https://github.com/Tooyz/moysklad/releases/tag/0.3.1
