### ISSUE TITLE
Фильтрация в отчетах по доп. полям и получение значений доп. полей

### ISSUE THREAD

**Issue by bigperson** [Tooyz/moysklad#22]
Добрый день. Подскажите можно ли как-то  получить отчет по остаткам с фильтрацией по доп. полям? В частности есть доп. поле чекбокс, необходимо получить все товары с этим полем true. Это возможно?

Также интересует возможность получить сразу значения доп. полей в отчете по остаткам.

**Comment by Tooyz** [comment]
@bigperson 
Добрый день, посмотрите документацию по отчетам [тут](https://online.moysklad.ru/api/remap/1.1/doc/index.html#%D0%BE%D1%82%D1%87%D1%91%D1%82-%D0%BE%D1%81%D1%82%D0%B0%D1%82%D0%BA%D0%B8-%D0%B2%D1%81%D0%B5-%D0%BE%D1%81%D1%82%D0%B0%D1%82%D0%BA%D0%B8-get) (кнопка "показать")

**Comment by AsheK** [comment]
@bigperson Здравствуйте. Нельзя. Отчёты не поддерживают возможность фильтрации по доп. полям товаров.

**Comment by bigperson** [comment]
Список ассортимент похоже тоже не поддерживает фильтрацию по доп. полям, ошибка 1034. Хотя мне как раз подошёл бы данный метод, придется городить кучу запросов. Пока открыл тикет в поддержку.

**Comment by AsheK** [comment]
@bigperson  Всё верно, не поддерживает. Но в данном случае вы можете воспользоваться параметрами `stockstore` и `scope`, тем самым получив ассортимент товаров по указанному складу, а так как сущность assortment показывает остатки, то вот, я считаю, это и есть решение вашей проблемы. И не придётся городить кучу запросов.

**Comment by bigperson** [comment]
@AsheK Увы stockstore  и scope мне не подойдет, т.к. нужны остатки не по складу а по товарам, у которых в доп. свойствах определенные значения. Причем в интерфейсе  моего склада такую выборку в остатках можно сделать.
