### ISSUE TITLE
Баг при получении позиций приемки (и вероятно, списаний)

### ISSUE THREAD

**Issue by Breedinf** [Tooyz/moysklad#23]
Здравствуйте! При попытке получить позиции приемки таким кодом:

```
$supply = Supply::query($this->sklad, QuerySpecs::create([
                'maxResults' => 1,
                'limit' => 1,
            ]))->withExpand(Expand::create(['positions']))
                ->withExpand(Expand::create(['agent']))
                ->byId($supply_id);
$positions = $supply->relationListQuery("positions")->getList();

```
возникает ошибка

> Unknown moysklad entity: supplyposition

**Comment by Breedinf** [comment]
и похоже, что подобным же образом не работает получение позиций розничного возврата

**Comment by Tooyz** [comment]
@Breedinf 
Извиняюсь что так долго.
https://github.com/Tooyz/moysklad/releases/tag/0.3.15
