### ISSUE TITLE
Проблема со связыванием отгрузок с заказом покупателя

### ISSUE THREAD

**Issue by Akar1n** [Tooyz/moysklad#3]
В МоемСкладе не проставляется связь при создании отгрузки.Проблема в том что customerOrder передается в  как customerorder,а api требует чтобы было customerOrder.

**Comment by Tooyz** [comment]
Завтра-послезавтра поправлю, видать не только с customerOrder такой косяк. 
Временно можно попробовать сделать так, после линкования заказа к отгрузке:
$links = $entity->links->getLinks();
$links->customerOrder = $links->customerorder;
unset( $links->customerorder );
$entity->links->replace($links);
