### ISSUE TITLE
Создать документ Отгрузка для заказа

### ISSUE THREAD

**Issue by mykolaim** [Tooyz/moysklad#30]
Добрый. 
Пытаюсь понять как создать документ - в readme в секции об этом не совсем понятно какой обьект в переменной $demand

**Comment by Tooyz** [comment]
@mykolaim 
Добрый. В переменной объект класса MoySklad\Entities\Documents\Movements\Demand

**Comment by mykolaim** [comment]
@Tooyz Спасибо, я это понял :) Давайте я уточню немного вопрос - как произвести инициализацию данного класса ?
`
    $storage = \MoySklad\MoySklad::getInstance($login, $password);

    $demand = \MoySklad\Entities\Documents\Movements\Demand::query($storage);
    $demand->getExportEmbeddedTemplates();
`
Вот так не получаеться, уточните плиз, а то для меня данный момент не очевиден.

**Comment by Tooyz** [comment]
@mykolaim 
`\MoySklad\Entities\Documents\Movements\Demand::query($storage)` возвращает `EntityQuery` объект, он используется для поиска и получения списков.
Что бы сделать запрос для получения всех demands можно сделать так:

```
    $storage = \MoySklad\MoySklad::getInstance($login, $password);
    $demands = \MoySklad\Entities\Documents\Movements\Demand::query($storage)->getList();
```

для получения конкретного - вот так: 

```
    $storage = \MoySklad\MoySklad::getInstance($login, $password);
    $demand = \MoySklad\Entities\Documents\Movements\Demand::query($storage)->byId($id);
```

Остальные примеры query в доках должны быть. Вот вам и объект `$demand`.
Ну и, конечно, никто не мешает его создать через `new Demand($storage, $attributes);`

**Comment by mykolaim** [comment]
@Tooyz еще момент - я пытаюсь для заказа создать документ Отгрузка;
Нахожу заказ, но документ не создает.
```
    $orders = \MoySklad\Entities\Documents\Orders\CustomerOrder::query($storage)->
        search('500');
    $order = $orders->get(0);
    $template = new \MoySklad\Entities\Documents\Templates\CustomTemplate($storage);
    $order->createPublication($template);
```
И спасибо большое за подробные обьяснения.
