### ISSUE TITLE
Добавить документ "Группа тех. карты"

### ISSUE THREAD

**Issue by elementfani** [Tooyz/moysklad#31]
При запросе `ProcessingPlan::query($this->moySkladInstance)->byId($id)` вылетает исключение

![image](https://user-images.githubusercontent.com/1698152/43720993-46fd5070-999a-11e8-9e45-5f5297df5ec5.png)

**Comment by Tooyz** [comment]
@elementfani Добавил в новом релизе, https://github.com/Tooyz/moysklad/releases/tag/0.4.7
