### ISSUE TITLE
Планируется ли поддержка публикации документов?

### ISSUE THREAD

**Issue by Akar1n** [Tooyz/moysklad#4]
Планируется ли поддержка публикации документов?
По идее не самая сложная часть апи и при этом очень нужная.

**Comment by Tooyz** [comment]
Это новая сущность? Странно что пропустил. На выходных попробую сделать.

**Comment by Tooyz** [comment]
@Akar1n 
В новом релизе у сущностей документов появились методы для работы с публикациями.
