### ISSUE TITLE
Ещё вопрос по использованию

### ISSUE THREAD

**Issue by walma** [Tooyz/moysklad#41]
Спасибо за библиотеку!
Вопрос такой - можно ли к
```
StockReport::byStore(
                $this->sklad,
                StockReportQuerySpecs::create(
                    [
                        'offset' => $offset,
                        'limit' => $maxResult,
                    ]
                )
            )
```
как-то прицепом вытащить инфу по товарам?
добавление 'expand' => Expand::create([Product::$entityName])
не помогает

**Comment by Tooyz** [comment]
@walma 
Добрый день, если expand не помогает и [тут](https://online.moysklad.ru/api/remap/1.1/doc/index.html#%D0%BE%D1%82%D1%87%D1%91%D1%82-%D0%BE%D1%81%D1%82%D0%B0%D1%82%D0%BA%D0%B8-%D0%BE%D1%81%D1%82%D0%B0%D1%82%D0%BA%D0%B8-%D0%BF%D0%BE-%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D0%B0%D0%BC-get) ничего полезного нет, то я даже не могу подсказать. Возможно стоит уточнить у саппорта о такой возможности.
