### ISSUE TITLE
Не возможно загрузить материалы и продукты

### ISSUE THREAD

**Issue by Takeshi80** [Tooyz/moysklad#42]
Для сущности `ProcessingPlan` 

При попытке получить **products** получаю `Uncaught MoySklad\Exceptions\UnknownEntityException: Unknown moysklad entity: processingplanresult in C:\xampp\htdocs\fl\vendor\tooyz\moysklad\src\Components\Fields\MetaField.php:37`

При попытке вытащить **materials** получаю `Uncaught MoySklad\Exceptions\UnknownEntityException: Unknown moysklad entity: processingplanmaterial in C:\xampp\htdocs\fl\vendor\tooyz\moysklad\src\Components\Fields\MetaField.php:37`

Это можно как-то пофиксить не со стороны библиотеки?
Код:
```
ProcessingPlan::query($storage)->getList()
    ->each(function (ProcessingPlan $plan) use ($storage) {
        $materials = $plan->relationListQuery("materials")->getList();
        print_r($materials); }
    );
```

**Comment by Tooyz** [comment]
#66
