### ISSUE TITLE
Добавление списка товаров при создании заказа покупателя

### ISSUE THREAD

**Issue by AlexSolonin** [Tooyz/moysklad#49]
Добрый день! В описании приведён пример создания заказа покупателя: $order = (new CustomerOrder($this->sklad))->buildCreation()
    ->addCounterparty($counterparty)
    ->addOrganization($organization)
    ->addPositionList($positions)
    ->execute();
уточнено, что мы можем добавить массив позиций ($positions).
Но метод addPositionList требует в переменной $positions наличие сущности EntityList, а не массива.
Я создаю эту сущность через new EntityList указывая  массив из сущностей Product, которые я создаю через new Product, но я не знаю как указать количество(quantity) каждой сущности Product. А без количества сделка не создаётся.

Как мне добавить это количество к каждой сущности Product В EntityList?
Можете привести нормальный пример создания заказа со списком товаров?
Спасибо!

**Comment by smadrom** [comment]
```
$products = new EntityList($storage);
	
$product = Product::query($storage)->byId('...');
	
$product->quantity = $item['quantity'];
$product->price = $item['price'] * 100;
$product->vat = $item['vat'];
$products->push($product);
	
->addPositionList($products)
```

**Comment by AlexSolonin** [comment]
Спасибо большое! Теперь всё ясно! ))
