### ISSUE TITLE
Баг с отгрузкой при привязке проекта

### ISSUE THREAD

**Issue by Akar1n** [Tooyz/moysklad#5]
При привязке проекта,падает скрипт 
[MoySklad\Exceptions\ApiResponseException]  ()/home/***/new/public_html/vendor/tooyz/moysklad/src/Components/Http/MoySkladHttpClient.php:187

**Comment by max-kut** [comment]
Проблема в классе `ApiResponseException`. 
В строке 22 класса `ApiResponseException` заменить свойство `$error->errorText` на `$error->error` и ошибка будет внятно отображаться.
