### ISSUE TITLE
Течет память при любых запросах!

### ISSUE THREAD

**Issue by timofeevkon** [Tooyz/moysklad#51]
Добрый день! 

RequestLog::setStorageSize(0); не работает!

![image_2019_10_29T10_46_25_040Z](https://user-images.githubusercontent.com/46534254/67768312-510ca400-fa63-11e9-9aa0-c5637458e5c0.png)

::history заполняется постоянно, сжирая много памяти. Исправьте пожалуйста!

![image_2019_10_29T10_48_45_072Z](https://user-images.githubusercontent.com/46534254/67768871-7c43c300-fa64-11e9-8717-eacb68f71eb2.png)

**Comment by Tooyz** [comment]
Добавлено RequestLog::setEnabled(false);
