### ISSUE TITLE
Ошибка преобразования float

### ISSUE THREAD

**Issue by spycrabo** [Tooyz/moysklad#52]
При получении товаров с нецелым значением цены неверно преобразуется значение.
Пример:
Данные в мойсклад:
![image](https://user-images.githubusercontent.com/30431331/68085912-2baeda00-fe57-11e9-8b1d-0149c2af6b19.png)
Данные при отладке апи:
![image](https://user-images.githubusercontent.com/30431331/68085922-4c772f80-fe57-11e9-9514-9a978e60b32c.png)
Ожидаемое значение: `13.75`
Предположил, что в мойсклад можно вводить с любым разделителем (точка или запятая) и проблема из-за этого, но в мойсклад при вводе точки происходит автоматическая замена на запятую, т.е. там разделитель всегда запятая.

**Comment by smadrom** [comment]
По-умолчанию цены округляются в копейки.

13,75 * 100 = 1375
1375.0 / 100 = 13.75
