### ISSUE TITLE
Получение списка товаров из Заказа покупателя

### ISSUE THREAD

**Issue by 094ikis09** [Tooyz/moysklad#55]
Как получить товары которые хранятся в заказе покупателя?

**Comment by smadrom** [comment]
В заказе храняться не товары, а позиции в которых есть ссылка на ассортимент, он же товар или его модификация.

В идеале используя экспанд это должно выглядеть вот так:

```
$customerOrder = CustomerOrder::query($storage, QuerySpecs::create([
    'maxResults' => 1,
    'expand' => Expand::create(['positions', 'positions.assortment']),
]))->byId('72e896e0-3c88-11e3-f188-7054d21a8d1e');


foreach ($customerOrder->relations->positions as $position)
{
    $position->assortment->id...
}
```
Но учитывая косяк библиотеки связанного с получанием rows реляционной сущности, сейчас это можно сделать только так: 

```
$customerOrder = CustomerOrder::query($storage)->byId('...');

$customerPositionList = $customerOrder->relationListQuery('positions')->getList();

foreach ($customerPositionList as $position)
{
    $assortment = $position->relations->fresh('assortment');
}
```

На фоне всей этой красоты рекомендую вам не использовать в данный момент времени данную библиотеку, по крайней мере пока нет нормальной поддержки от людей которые в этом заинтересованы. Берите любой http клиент и читайте доку моего склада, это сначала не так удобно будет, но избавит вас от головой боли допила либы.
