### ISSUE TITLE
Как вообще работать со всем этим?!

### ISSUE THREAD

**Issue by evgeniyefimchenko** [Tooyz/moysklad#62]
Вообще не понятен процесс работы с данным SDK. Потратил 3 часа времени и понял что проще своё решение писать, что займёт меньше времени. Просто список заказов непонятно как получить, не говоря уже об обновлении, каких то данных. Похоже что всё это делалось под себя и исключительно для себя. Ни толковых примеров ни адекватной документации. Звёзды похоже знакомые понаставили или заказные.

**Comment by max-kut** [comment]
Это Ваше субъективное мнение. 
Возможно действительно на начальном этапе разобраться в архитектуре библиотеки сложновато (сам таким был). Для каждой сущности или коллекции сущностей есть свой класс. Но прежде чем работать с библиотекой, нужно разобраться с документацией api МойСклад, и станет понятней.

P.S. разработчика лично не знаю, но плюс ему в карму, что выкатил в opensource такую библиотеку, т.к. работы по ней было проведено много. Плюс в карму также тем, кто формирует pull реквесты с исправлениями или улучшениями

**Comment by web-mehanik** [comment]
изучите ООП и все встанет на свои места, это решение легко маштабируется и сделано неплохо
