### ISSUE TITLE
Нет сущности для работы с перемещением

### ISSUE THREAD

**Issue by matiosfree** [Tooyz/moysklad#68]
Добрый день. Отсутствует сущность для работы с перемещением:
https://dev.moysklad.ru/doc/api/remap/1.1/#%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D1%8F

Видимо нужно добавить новый класс Entities/Documents/Movements/Move.php

**Comment by Tooyz** [comment]
@matiosfree Добрый, как правило обычно этого достаточно. Если не сложно, сделайте, пожалуйста эту правку и пришлите pull-request если всё ок

**Comment by matiosfree** [comment]
@Tooyz Добавил PR. Сделал по аналогии с Оприходованием (EnterPosition\Enter)

**Comment by matiosfree** [comment]
Спасибо за мерж. Можете пожалуйста обновить к packagist, так как там написано:
This package is not auto-updated.
Last update: 2020-06-12 19:21:37 UTC

Видимо его нужно в ручную апдейтить.

**Comment by Tooyz** [comment]
@matiosfree готово
