### ISSUE TITLE
Получение всех сущностей.

### ISSUE THREAD

**Issue by alexeyvolodin** [Tooyz/moysklad#70]
Добрый день, подскажите как правильно работать со списком всех сущностей. У апи есть ограничение на выдачу товаров, т.е. за раз все товары получить не получается.
Есть ли какие то методы для перехода на следующую страницу или надо сначала получить размер (кол-во сущностей) и потом в цикле пока не достигнет конца изменять offset?

**Comment by Tooyz** [comment]
Добрый. Если я правильно помню, то получение всех сущностей без ручной пагинации можно сделать если у передаваемого QuerySpecs будет maxResults равное 0. Типо того
```
Product::query($sklad, QuerySpecs::create([
            'maxResults' => 0
        ]))->getList();

```
