### ISSUE TITLE
Не работает получение изображений 

### ISSUE THREAD

**Issue by azverin-sb** [Tooyz/moysklad#75]
При вызове метода $product->image->download не происходит авторизации.
GuzzleHttp \ Exception \ ClientException (401)
Client error: `GET https://online.moysklad.ru/api/remap/1.1/download/XXXXXXXXXX` resulted in a `401 Unauthorized` response

Полагаю это из-за того что в методе 
```
public function download($saveFile, $size = 'normal'){
        if ( $link = $this->getDownloadLink($size) ){
            $filePath = fopen($saveFile,'w+');
            $client = new Client();
            $response = $client->get($link, [RequestOptions::SINK => $filePath]);
            return $response->getStatusCode();
        }
        throw new \Exception("Image does not have a $size size link. Try to refresh hosting entity");
    }
```

Идет  $client = new Client(); без параметров для авторизации

**Comment by Tooyz** [comment]
#89
