### ISSUE TITLE
100+ позиций в заказе

### ISSUE THREAD

**Issue by nazmutdinov-rafael** [Tooyz/moysklad#88]
Здравствуйте!
Как добавить 100+ позиций в заказ?

Создаю заказ с первым 100 позициями с помощью функции:

```
order = (new CustomerOrder($sklad, ['description' => 'test']))
->buildCreation()
->addCounterparty($counterparty)
->addOrganization($org)
->addPositionList($mcOrderProducts)
->addStore($store)
->addEmployee($employee)
->execute();
```

Создается успешно. Далее отправляю вторую сотню позиций с помощью:

```
$order->buildUpdate()
->addPositionList($mcOrderProducts2)
->execute();
```

Но вместо того, чтобы добавлять в заказ позиции, он заменяет те позиции, которые уже были в заказе.

Нагуглил ответ в саппорте МойСклад:
https://support.moysklad.ru/hc/ru/community/posts/360009822057-Почему-entity-customerorder-id-positions-не-принимает-100-позиций-

Но возможности реализации такого решения в библиотеке не нашел.

Какие есть варианты? Как решить задачу?

**Comment by Shusev** [comment]
$order->buildUpdate()
->attachPositions($mcOrderProducts)
->execute();

**Comment by Shusev** [comment]
> @Shusev получится ли добавить PR?

https://github.com/Tooyz/moysklad/pull/100
