### ISSUE TITLE
Баг в QuerySpecs

### ISSUE THREAD

**Issue by Breedinf** [Tooyz/moysklad#9]
Если я правильно понимаю, то три варианта кода:
$product = Product::query($this->sklad, QuerySpecs::create([
                'maxResults' => 1,
                'limit' => 1,
            ]))->withExpand(Expand::create(['productFolder']))
               ->filter((new FilterQuery())
               ->eq("id", $product_id))->get(0);

и

$product = Product::query($this->sklad, QuerySpecs::create([
                'maxResults' => 1,
                'limit' => 1,
            ]))->withExpand(Expand::create(['productFolder']))->byId($product_id);

и

$product = Product::query($this->sklad, QuerySpecs::create([
                'maxResults' => 1,
                'expand' => Expand::create(['productFolder']),
                'limit' => 1,
            ]))->filter((new FilterQuery())
               ->eq("id", $product_id))->get(0);

должны давать одинаковый результат, но во втором и третьем варианте 
$product->relations->productFolder->id пустой, а в первом содержит id группы товаров.

Выглядит, как баг, или я где-то не прав?

**Comment by Tooyz** [comment]
С виду Вы правы, постараюсь вечерком глянуть.

**Comment by Tooyz** [comment]
Выкатил релиз, обновитесь.
