### ISSUE TITLE
При создании заказа не прописывается его статус

### ISSUE THREAD

**Issue by eugene-bulanov** [Tooyz/moysklad#91]
Пробую получить статус по ID:

    $orderStatus = State::query($this->instance)
      ->byId($stateID)
      ->transformToClass(State::class);

$stateID верный.

Но ловлю Exception с ошибкой "Ошибка в адресе запроса".
Что-то не так с адресацией у этой сущности. По идее запрос должен быть сюда:
https://online.moysklad.ru/api/remap/1.2/entity/counterparty/metadata

**Comment by Tooyz** [comment]
У вас по ссылке запрос контрагента, соответственно код должен быть такой
```
CounterParty::query($this->instance)->byId($id);
```

**Comment by eugene-bulanov** [comment]
Да вот как раз нужен не он, а статус. Просто в документации МойСклад именно такой адрес для статуса:

https://dev.moysklad.ru/doc/api/remap/1.2/dictionaries/#suschnosti-statusy-dokumentow-poluchit-metadannye

**Comment by Tooyz** [comment]
```Counterparty::getMetaData($this->instance);```
Возможно это подойдёт

**Comment by eugene-bulanov** [comment]
Выкрутился вот так:
CustomerOrder::getMetaData($this->instance)->states->get(4);
Но по порядковому номеру не круто, конечно, получать. Как-то можно его по ID склада получить? Без перебора массива.

**Comment by Tooyz** [comment]
Можно использовать filter на entityList. Другого способа пока нет
