### ISSUE TITLE
Как при создании заказа указывать владельца заказа?

### ISSUE THREAD

**Issue by web-mehanik** [Tooyz/moysklad#92]
Есть проблема - могу назначить владельца заказа после создания заказа, но не получается сразу его указать перед созданием.
addEmployee() не работает, если просто передаю массив 'owner' => ['meta' => массив_метаданных] владелец тоже не присваивается, может кто знает ответ чтобы мне не копаться в коде?

**Comment by web-mehanik** [comment]
немного поспешил с вопросом, если кому пригодится, то нужно в класс abstract class AbstractMutationBuilder
добавить метод
/**
     * @param Employee $employee
     * @param LinkingSpecs|null $specs
     * @return AbstractMutationBuilder
     * @throws \Exception
     */
    public function addOwner(Employee $employee, LinkingSpecs $specs = null){
        return $this->simpleLink($employee, $specs, LinkingSpecs::create([
            "name" => "owner"
        ]));
    }

и его использовать для назначения владельца заказу, как оказалось, решение лежало на поверхности

**Comment by Tooyz** [comment]
Добавил в репозиторий, спасибо
