### ISSUE TITLE
InvalidUrlException при валидных картинках

### ISSUE THREAD

**Issue by bigperson** [Tooyz/moysklad#95]
Пытаюсь добавить картинку, но ловлю исключение
MoySklad\Exceptions\InvalidUrlException: Url https://....ru/files/products/10617/conversions/T94v2__500х410-thumb.jpg is invalid in ...laravel/vendor/tooyz/moysklad/src/Components/Fields/ImageField.php:18

**Comment by Tooyz** [comment]
Таким образом? ```attachImage(ImageField::createFromUrl(
    "http://url.ru/img.jpg"
));```
для валидации используется FILTER_VALIDATE_URL, валидный url должен проходить эту проверку

**Comment by bigperson** [comment]
да, так
вопрос в чем невалидность в строке files/products/10617/conversions/T94v2__500х410-thumb.jpg ?

**Comment by Tooyz** [comment]
Ещё раз уточню: валидацию функцией ```filter_var($url, FILTER_VALIDATE_URL)``` проходит?
Конкретно ```files/products/10617/conversions/T94v2__500х410-thumb.jpg``` вообще не url. Если это файл на файловой системе -- нужно использовать ```ImageField:: createFromPath```
